export const siteUrl = "https://dev-muhammad.vercel.app";

export const projects = [
  {
    slug: "sablebuild",
    name: "Sable Build",
    seoTitle: "Sable Build | Visual Builder With Multi-Stack Export",
    description: "An in-progress visual website and application builder with multi-stack code export.",
    image: "/case-studies/sable/home.png",
    liveUrl: "https://sablebuild.vercel.app",
    keywords: ["Next.js", "Zustand", "MongoDB", "Visual website builder", "Code export"],
  },
  {
    slug: "emberoak",
    name: "Ember Oak",
    seoTitle: "Ember Oak | Modern Restaurant Operations & Ordering",
    description: "A restaurant management demo with ordering, reservations, catering, reviews, and admin tools.",
    image: "/case-studies/emberoak/home.png",
    liveUrl: "https://emberoak-two.vercel.app",
    keywords: ["Next.js", "MongoDB", "Stripe", "Restaurant management"],
  },
  {
    slug: "awaza",
    name: "Awaza",
    seoTitle: "Awaza | Real-Time Social PWA for Messaging & Sharing",
    description: "A social media progressive web application with real-time chat, notifications, and social interactions.",
    image: "/case-studies/awaza/home.png",
    liveUrl: "https://awaza-social.vercel.app",
    keywords: ["Next.js", "Firebase", "MongoDB", "Progressive web application"],
  },
  {
    slug: "fluentyx",
    name: "Fluentyx",
    seoTitle: "Fluentyx | AI Arabic Learning, Practice & Revision",
    description: "An Arabic learning platform with interactive exercises, revision tools, an AI tutor, and handwriting classification.",
    image: "/case-studies/fluentyx/home.png",
    liveUrl: "https://fluentyx.vercel.app",
    keywords: ["Next.js", "PyTorch", "LangChain", "Arabic learning", "Artificial intelligence"],
  },
  {
    slug: "expense-tracker",
    name: "Expense Tracker",
    seoTitle: "Expense Tracker | React Native Personal Finance App",
    description: "A React Native mobile app for tracking income, expenses, wallets, and spending statistics.",
    image: "/case-studies/expense/home.jpeg",
    keywords: ["React Native", "Expo", "Firebase", "Cloudinary", "Expense tracking"],
    applicationCategory: "FinanceApplication",
    operatingSystem: "Android, iOS",
  },
  {
    slug: "macrozone",
    name: "Macrozone",
    seoTitle: "Macrozone | Simple React Native Macro Tracker",
    description: "A lightweight React Native learning project for recording meals and tracking daily calories and macronutrients.",
    image: "/case-studies/macrozone/home.jpeg",
    keywords: ["React Native", "Expo", "AsyncStorage", "Nutrition tracking", "Mobile app"],
    applicationCategory: "HealthApplication",
    operatingSystem: "Android, iOS",
  },
  {
    slug: "tebre",
    name: "TeBre",
    seoTitle: "TeBre | AI-Assisted Ebook Production Desktop Software",
    description: "An Electron desktop workspace that helps ebook agencies manage, write, polish, design, and export KDP-ready books.",
    image: "/case-studies/tebre/dashboard.png",
    keywords: ["Electron", "React", "SQLite", "AI writing", "Ebook production", "Amazon KDP"],
    applicationCategory: "BusinessApplication",
    operatingSystem: "Desktop",
  },
  {
    slug: "sparkio",
    name: "Sparkio",
    seoTitle: "Sparkio | Ecommerce With Fuzzy Search & Order Tracking",
    description: "A full ecommerce store with fuzzy search, advanced filters, cart, orders, tracking, and customer accounts.",
    image: "/case-studies/sparkio/home.png",
    liveUrl: "https://sparkio.store",
    keywords: ["Next.js", "MongoDB", "Nodemailer", "Ecommerce", "Fuzzy search"],
  },
  {
    slug: "glowfarm",
    name: "GlowFarm",
    seoTitle: "GlowFarm | Cinematic Lighting Website Built With Motion",
    description: "An animation-focused concept website for a fictional lighting brand.",
    image: "/case-studies/glowfarm/hero.png",
    liveUrl: "https://glowfarm.vercel.app",
    keywords: ["Next.js", "Framer Motion", "Tailwind CSS", "Web animation"],
  },
  {
    slug: "rag",
    name: "RAG Agent",
    seoTitle: "RAG Agent | Grounded AI Answers With LangChain & FAISS",
    description: "A retrieval-augmented generation assistant that answers questions using indexed knowledge and relevant context.",
    image: "/case-studies/rag-agent/rag-agent.png",
    liveUrl: "https://techdxon.com/ai",
    keywords: ["Python", "LangChain", "Hugging Face", "FAISS", "Retrieval-augmented generation"],
  },
  {
    slug: "vendra",
    name: "Vendra",
    seoTitle: "Vendra | Multi-Branch Retail POS & Inventory System",
    description: "A retail operations platform connecting point-of-sale, inventory, purchasing, customers, staff, branches, and performance reporting.",
    image: "/case-studies/vendra/dashboard.png",
    liveUrl: "https://vendra-pos.vercel.app/",
    keywords: ["Next.js", "React", "Tailwind CSS", "Retail POS", "Inventory management", "Multi-branch retail"],
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
  },
  {
    slug: "skytech",
    name: "SkyTech Official Website",
    seoTitle: "SkyTech | Responsive Software Agency Website Experience",
    description: "A responsive company website presenting software services, packages, careers, and contact options.",
    image: "/case-studies/skytech/home.png",
    liveUrl: "https://skytech.com.pk",
    keywords: ["React", "Vanilla CSS", "EmailJS", "AOS", "Business website"],
  },
];

export const createProjectSchema = (project) => ({
  "@type": ["Project", "SoftwareApplication"],
  "@id": `${siteUrl}/case-study/${project.slug}#project`,
  name: project.name,
  description: project.description,
  url: `${siteUrl}/case-study/${project.slug}`,
  mainEntityOfPage: `${siteUrl}/case-study/${project.slug}#webpage`,
  image: `${siteUrl}${project.image}`,
  ...(project.liveUrl ? { sameAs: project.liveUrl } : {}),
  applicationCategory: project.applicationCategory || "WebApplication",
  operatingSystem: project.operatingSystem || "Web",
  author: { "@id": `${siteUrl}/#person` },
  creator: { "@id": `${siteUrl}/#person` },
  founder: { "@id": `${siteUrl}/#person` },
  keywords: project.keywords.join(", "),
  inLanguage: "en",
});

export const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ProfilePage",
      "@id": `${siteUrl}/#profilepage`,
      url: siteUrl,
      name: "Muhammad Portfolio | Fullstack Web & Applied AI Developer",
      description:
        "Muhammad's professional portfolio, featuring full-stack projects, AI tools, services, and modern web applications.",
      isPartOf: { "@id": `${siteUrl}/#website` },
      mainEntity: { "@id": `${siteUrl}/#person` },
      about: { "@id": `${siteUrl}/#person` },
      primaryImageOfPage: { "@id": `${siteUrl}/#profile-image` },
      inLanguage: "en",
    },
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: "Muhammad Portfolio",
      alternateName: [
        "Unfathomable",
        "Unfathomable-08",
        "Unfathomable_08",
        "Unfathomable08",
      ],
      description:
        "Portfolio of Muhammad, a full-stack web and applied AI developer.",
      publisher: { "@id": `${siteUrl}/#person` },
      author: { "@id": `${siteUrl}/#person` },
      inLanguage: "en",
    },
    {
      "@type": "Person",
      "@id": `${siteUrl}/#person`,
      name: "Muhammad",
      alternateName: [
        "Unfathomable",
        "Unfathomable-08",
        "Unfathomable_08",
        "Unfathomable08",
      ],
      identifier: "Unfathomable-08",
      url: siteUrl,
      image: { "@id": `${siteUrl}/#profile-image` },
      jobTitle: ["Fullstack Web Developer", "Applied AI Developer"],
      description:
        "Full-stack web and app developer specializing in modern user interfaces, scalable back-end systems, and applied AI solutions.",
      email: "mailto:muhammad124711@gmail.com",
      telephone: "+92 328 2279743",
      sameAs: [
        "https://github.com/Unfathomable-08",
        "https://x.com/unfathomable_08",
        "https://instagram.com/unfathomable_08",
        "https://linkedin.com/in/muhammad-abasi-6b6884350",
      ],
      knowsAbout: [
        "Full-stack web development",
        "Applied artificial intelligence",
        "React",
        "Next.js",
        "Node.js",
        "Express.js",
        "Python",
        "MongoDB",
        "SQL",
        "Progressive web applications",
        "React Native",
        "AI agents",
      ],
      worksFor: [
        {
          "@type": "Organization",
          name: "TechDxon",
          url: "https://techdxon.com",
        },
        {
          "@type": "Organization",
          name: "Techno Rivals",
          url: "https://techno-rivals.com",
        },
      ],
      hasOfferCatalog: { "@id": `${siteUrl}/#services` },
    },
    {
      "@type": "ImageObject",
      "@id": `${siteUrl}/#profile-image`,
      url: `${siteUrl}/og-square.png`,
      contentUrl: `${siteUrl}/og-square.png`,
      width: 1200,
      height: 1200,
      caption: "Muhammad Portfolio",
    },
    {
      "@type": "OfferCatalog",
      "@id": `${siteUrl}/#services`,
      name: "Development services",
      url: `${siteUrl}/services`,
      itemListElement: [
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            "@id": `${siteUrl}/#web-development`,
            name: "Enterprise-Grade Web Development",
            serviceType: "Full-stack web development",
            description:
              "High-performance, scalable websites built with React, Next.js, and robust back-end architectures.",
            provider: { "@id": `${siteUrl}/#person` },
            url: `${siteUrl}/services`,
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            "@id": `${siteUrl}/#desktop-development`,
            name: "Desktop Software Development",
            serviceType: "Cross-platform desktop software development",
            description:
              "Desktop software development for Windows, macOS, and Linux.",
            provider: { "@id": `${siteUrl}/#person` },
            url: `${siteUrl}/services`,
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            "@id": `${siteUrl}/#pwa-development`,
            name: "Progressive Web Apps (PWAs)",
            serviceType: "Progressive web application development",
            description:
              "App-like web experiences with offline support, push notifications, and responsive performance across devices.",
            provider: { "@id": `${siteUrl}/#person` },
            url: `${siteUrl}/services`,
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            "@id": `${siteUrl}/#ai-agents`,
            name: "AI Agents",
            serviceType: "AI agent development and automation",
            description:
              "AI agents that automate tasks, process data, and handle repetitive work using AI tools, APIs, and custom scripts.",
            provider: { "@id": `${siteUrl}/#person` },
            url: `${siteUrl}/services`,
          },
        },
      ],
    },
    {
      "@type": "ItemList",
      "@id": `${siteUrl}/projects#project-list`,
      url: `${siteUrl}/projects`,
      name: "Featured development projects",
      description: "Full-stack applications, AI tools, ecommerce platforms, and animated web experiences created by Muhammad.",
      numberOfItems: projects.length,
      itemListElement: projects.map((project, index) => ({
        "@type": "ListItem",
        position: index + 1,
        item: { "@id": `${siteUrl}/case-study/${project.slug}#project` },
      })),
    },
    ...projects.map(createProjectSchema),
  ],
};
